version: '3'

services:
  zap2xml:
    image: ghcr.io/kj4ezj/zap2xml:v0.1.4
    restart: always
    volumes:
        - /xmltvdata:/data
    environment:
        - USERNAME=someone@example.com
        - PASSWORD=hunter2
        - XMLTV_FILENAME=tv-guide.xml
